### ISSUE TITLE
where is annotation?

### ISSUE THREAD

**Issue by tyone777** [monjurulkarim/ROL_Dataset#1]
In your paper, the dataset contains spatial, temporal, and categorical annotations with the accident, object, and scene-level attributes. 

But this repository seems not to exist annotation.
Where is annotation?

**Comment by monjurulkarim** [comment]
You can find the spatial and temporal annotation in our provided feature file at [Download](https://github.com/monjurulkarim/ROL_Dataset#download)

for each feature file the following data are provided:

> **feature:** Extracted 2048-dim appearance features with shape (100, 31, 2048). It contains frame-level feature with shape (100, 1, 2048) and 19 box-level features with shape (100, 30, 2048)
> **detection:** Detected bounding boxes with shape (100, 30, 6), where the last dim denotes (object_tracking_id, x1, y1, x2, y2, cls), where cls =0 represents non risky and cls = 1 represents risky object.)
> **vid_id** : The video name for current feature file
> **toa:** time of accident when actual crash begins
> **flow_feat** : extracted the flow feature in the same format as the appearance feature

To use the annotation you will need the `detection,` and `toa`.

Thank you for your interest in our repository. The detail instruction on how to use the repository and the categorical annotation will be added soon.

**Comment by tyone777** [comment]
Thank you for replying.
In the present circumstances, annotation only include whether risky or non-risky.
I'm looking forward to seeing categorical annotation.
