### ISSUE TITLE
dataset feature issue

### ISSUE THREAD

**Issue by jala1494** [monjurulkarim/ROL_Dataset#2]
how can I get the flow feature?
There are 2 datasets
CNN and Raw dataset.
I tried to make CNN dataset from rawdataset.
but there's no flow_feature in feat_extract.py
I wonder I can make dataset from feat_extract.py

**Comment by lingyixia** [comment]
I am also confused in get feature frow rawdataset, do you know how?

**Comment by xswings** [comment]
I am also confused in getting feature frow rawdataset, do you know how?

**Comment by jala1494** [comment]
Use RAFT and Restnet
The flow feature shape is [100,31,2048]
100 means frame,
31 
- first row global frowfeature
- 30 object flow feature
2048 is made by (1)RAFT and (2)resent, (3)feature extract code
